# Manipulação de arrays Numpy

### Importando o NumPy

In [ ]:
!pip install numpy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [6]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([ 81,  87, 175,  64,  28, 113,  92,   3, 197, 159, 185, 157])

In [7]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[168,  45, 136,  73],
       [ 19, 116, 117,  87],
       [ 10, 140,  28,  16]])

In [8]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[  7, 154, 154,  18, 122,  11],
        [ 46, 163, 170,  76,  43,  93],
        [183,  23,  59, 114,   3,  85]],

       [[ 97, 140, 105,   7,  61, 156],
        [185, 152, 192,  64,  83, 191],
        [182, 127, 148,  57,  42, 161]]])

In [9]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1,  87, 175,  64,  28, 113,  92,   3, 197, 159, 185, 157])

In [10]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[168,  45, 136,  73],
       [ 19, 116,  -1,  87],
       [ 10, 140,  28,  16]])

In [11]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[  7, 154, 154,  18, 122,  11],
        [ 46, 163, 170,  76,  43,  93],
        [183,  23,  59, 114,   3,  85]],

       [[ 97, 140, 105,   7,  61, 156],
        [185, 152, 192,  64,  83, 191],
        [182, 127, 148,  57,  -1, 161]]])

In [12]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
a1D_modificado

array([ -1,  87, 175,  64,  28, 113,  92,   3, 197, 159, 185, 157, 100,
       130])

In [13]:
a1D # a1D não foi modificado

array([ -1,  87, 175,  64,  28, 113,  92,   3, 197, 159, 185, 157])

In [15]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([168,  45, 136,  73,  19, 116,  -1,  87,  10, 140,  28,  16, 100,
       130])

In [16]:
a2D_modificado.ndim

1

In [14]:
a2D # a2D não foi modificado

array([[168,  45, 136,  73],
       [ 19, 116,  -1,  87],
       [ 10, 140,  28,  16]])

In [17]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([  7, 154, 154,  18, 122,  11,  46, 163, 170,  76,  43,  93, 183,
        23,  59, 114,   3,  85,  97, 140, 105,   7,  61, 156, 185, 152,
       192,  64,  83, 191, 182, 127, 148,  57,  -1, 161, 100, 130])

In [18]:
a3D # a3D não foi modificado

array([[[  7, 154, 154,  18, 122,  11],
        [ 46, 163, 170,  76,  43,  93],
        [183,  23,  59, 114,   3,  85]],

       [[ 97, 140, 105,   7,  61, 156],
        [185, 152, 192,  64,  83, 191],
        [182, 127, 148,  57,  -1, 161]]])

In [19]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1  87 175  64  28 113  92   3 197 159 185 157 100 130]
[175  28 113  92   3 197 159 185 157 100 130]


### Comparação entre arrays

In [20]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [21]:
c1D = np.random.randint(1,10,20)
c1D

array([1, 1, 9, 2, 3, 6, 9, 3, 6, 5, 7, 3, 4, 9, 6, 6, 9, 5, 5, 8])

In [22]:
c1D == 5

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False])

In [23]:
c1D[c1D == 5]

array([5, 5, 5])

### Operações entre arrays e escalares

In [24]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [28]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [29]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [30]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [31]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [32]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [33]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [34]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [35]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [36]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [37]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [38]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [39]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [40]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [41]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
raiz1D = np.sqrt(g1D)
raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

In [43]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[10,  1, 61, 97, 75, 26, 76, 38, 21, 23],
       [44, 54, 86, 92, 61, 34, 61, 83, 62, 58],
       [77, 68, 29, 91, 13, 31, 22, 21, 69, 25],
       [68, 71, 97, 72, 20, 59, 53, 84,  1, 72],
       [54, 96, 99, 82, 91, 44, 35,  3, 91, 54]])

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [44]:
# Soma de todos os elementos
d2D.sum()

2755

In [45]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([253, 290, 372, 434, 260, 194, 247, 229, 244, 232])

In [46]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([428, 635, 446, 597, 649])

In [47]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([253, 290, 372, 434, 260, 194, 247, 229, 244, 232])

In [48]:
# Retorna o menor valor geral
d2D.min()

1

In [49]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([10,  1, 29, 72, 13, 26, 22,  3,  1, 23])

In [50]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([ 1, 34, 13,  1,  3])

In [51]:
# Retorna o maior valor geral
d2D.max()

99

In [52]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([77, 96, 99, 97, 91, 59, 76, 84, 91, 72])

In [53]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([97, 92, 91, 97, 99])

In [54]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  10,   11,   72,  169,  244,  270,  346,  384,  405,  428,  472,
        526,  612,  704,  765,  799,  860,  943, 1005, 1063, 1140, 1208,
       1237, 1328, 1341, 1372, 1394, 1415, 1484, 1509, 1577, 1648, 1745,
       1817, 1837, 1896, 1949, 2033, 2034, 2106, 2160, 2256, 2355, 2437,
       2528, 2572, 2607, 2610, 2701, 2755])

In [55]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 10,   1,  61,  97,  75,  26,  76,  38,  21,  23],
       [ 54,  55, 147, 189, 136,  60, 137, 121,  83,  81],
       [131, 123, 176, 280, 149,  91, 159, 142, 152, 106],
       [199, 194, 273, 352, 169, 150, 212, 226, 153, 178],
       [253, 290, 372, 434, 260, 194, 247, 229, 244, 232]])

In [56]:
d2D

array([[10,  1, 61, 97, 75, 26, 76, 38, 21, 23],
       [44, 54, 86, 92, 61, 34, 61, 83, 62, 58],
       [77, 68, 29, 91, 13, 31, 22, 21, 69, 25],
       [68, 71, 97, 72, 20, 59, 53, 84,  1, 72],
       [54, 96, 99, 82, 91, 44, 35,  3, 91, 54]])

In [57]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 10,  11,  72, 169, 244, 270, 346, 384, 405, 428],
       [ 44,  98, 184, 276, 337, 371, 432, 515, 577, 635],
       [ 77, 145, 174, 265, 278, 309, 331, 352, 421, 446],
       [ 68, 139, 236, 308, 328, 387, 440, 524, 525, 597],
       [ 54, 150, 249, 331, 422, 466, 501, 504, 595, 649]])

In [58]:
# Retorna a média aritmética
d2D.mean()

55.1

In [59]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([50.6, 58. , 74.4, 86.8, 52. , 38.8, 49.4, 45.8, 48.8, 46.4])

In [60]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([42.8, 63.5, 44.6, 59.7, 64.9])

In [61]:
# Retorna o desvio padrão
d2D.std()

28.614157335137442

In [62]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([23.25166661, 31.5531298 , 26.4242313 ,  8.84081444, 30.58103988,
       11.68588893, 19.04310899, 32.71330005, 32.926585  , 19.25201288])

In [63]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([30.66528982, 17.56274466, 26.87824399, 27.47380571, 30.30659994])

In [64]:
# Retorna a mediana (geral)
np.median(d2D)

60.0

In [65]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([54., 68., 86., 91., 61., 34., 53., 38., 62., 54.])

In [66]:
# Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([32. , 61. , 30. , 69.5, 68. ])

### Copiando e concatenando arrays

In [67]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[48, 20, 38, 42, 35],
       [31, 35, 37, 14, 13],
       [34, 27,  9, 15, 48],
       [11,  7,  5, 44, 34]])

In [68]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[77, 76, 59, 84, 83],
       [59, 61, 67, 72, 98],
       [58, 57, 92, 84, 55],
       [69, 82, 59, 85, 85]])

In [69]:
c2D = a2D
c2D

array([[48, 20, 38, 42, 35],
       [31, 35, 37, 14, 13],
       [34, 27,  9, 15, 48],
       [11,  7,  5, 44, 34]])

In [73]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[48, 20, 38, 42, 35],
       [31, 35, 37, -1, -1],
       [34, 27, -1, -1, 48],
       [-1, -1, -1, 44, 34]])

In [74]:
a2D 

array([[17, 45, 21,  4, 17],
       [34, 13, 19, 42, 30],
       [47, 15, 30, 44, 36],
       [42, 10, 41, 21, 46]])

Os elementos de a2D também foram alterados. :-(

In [75]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[ 7, 20, 10, 38, 14],
       [19,  1, 45, 34, 32],
       [13, 22, 26, 37,  4],
       [11, 14, 19, 33, 11]])

In [77]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[ 7, 20, 10, 38, 14],
       [19,  1, 45, 34, 32],
       [13, 22, 26, 37,  4],
       [11, 14, 19, 33, 11]])

In [78]:
c2D[c2D < 20] = -1
c2D

array([[-1, 20, -1, 38, -1],
       [-1, -1, 45, 34, 32],
       [-1, 22, 26, 37, -1],
       [-1, -1, -1, 33, -1]])

In [79]:
a2D

array([[ 7, 20, 10, 38, 14],
       [19,  1, 45, 34, 32],
       [13, 22, 26, 37,  4],
       [11, 14, 19, 33, 11]])

Agora sim!!!

### Ordenando os elementos de um array

In [80]:
a1D = np.random.randint(1,100, 15)
a1D

array([17, 71, 33, 45, 45, 80, 78, 11, 56, 32, 21, 30, 38, 17, 12])

In [81]:
a1D.sort()
a1D

array([11, 12, 17, 17, 21, 30, 32, 33, 38, 45, 45, 56, 71, 78, 80])

In [82]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[13, 64, 82, 28, 53, 47, 44,  5, 85, 63],
       [96, 98, 87, 68, 99, 73, 66, 40, 51, 17],
       [11, 54, 43, 49, 37, 26, 52, 80, 34, 88],
       [51, 22, 75, 31, 54, 88, 57, 80, 89, 57],
       [80,  4,  5, 73, 81, 71, 47, 48, 40, 92],
       [45, 65, 49, 12, 83, 49, 35, 53, 44, 89]])

In [83]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[ 5, 13, 28, 44, 47, 53, 63, 64, 82, 85],
       [17, 40, 51, 66, 68, 73, 87, 96, 98, 99],
       [11, 26, 34, 37, 43, 49, 52, 54, 80, 88],
       [22, 31, 51, 54, 57, 57, 75, 80, 88, 89],
       [ 4,  5, 40, 47, 48, 71, 73, 80, 81, 92],
       [12, 35, 44, 45, 49, 49, 53, 65, 83, 89]])

In [84]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[ 4,  5, 28, 37, 43, 49, 52, 54, 80, 85],
       [ 5, 13, 34, 44, 47, 49, 53, 64, 81, 88],
       [11, 26, 40, 45, 48, 53, 63, 65, 82, 89],
       [12, 31, 44, 47, 49, 57, 73, 80, 83, 89],
       [17, 35, 51, 54, 57, 71, 75, 80, 88, 92],
       [22, 40, 51, 66, 68, 73, 87, 96, 98, 99]])

In [85]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[61, 78,  5, 44, 91, 69, 56, 43, 40, 62],
       [83, 41, 12, 16, 34, 47, 35,  3, 68, 39],
       [90, 84, 37, 25, 31, 96, 82, 25, 10, 27],
       [84, 98, 52, 81, 37, 81, 91, 20, 71, 13],
       [10, 84, 74, 80, 52, 94, 99,  9, 25, 12],
       [87, 62, 55,  8,  5,  8, 59,  1,  2,  4]])

In [86]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[ 5, 40, 43, 44, 56, 61, 62, 69, 78, 91],
       [ 3, 12, 16, 34, 35, 39, 41, 47, 68, 83],
       [10, 25, 25, 27, 31, 37, 82, 84, 90, 96],
       [13, 20, 37, 52, 71, 81, 81, 84, 91, 98],
       [ 9, 10, 12, 25, 52, 74, 80, 84, 94, 99],
       [ 1,  2,  4,  5,  8,  8, 55, 59, 62, 87]])

### Transposição de arrays

In [87]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [89]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [91]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Mudando o formato de um array - reshape()

In [92]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [94]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(2, 12)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [97]:
a2D_4x6 = a1D.reshape(4,6)
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [98]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [99]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [100]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [101]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [102]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[ 83,  32,  24,  65,  80,  76,  10,  36,  58],
       [ 65,  68,  52,  47,  38,  69, 100,  15,  10],
       [ 19,  61,  38,  87,  58,  84,  83,  63,  70]])

In [103]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[58, 37, 49, 82, 93, 88, 82, 99, 70],
       [ 5, 49, 87, 65, 72, 17, 73, 82, 98],
       [50,  3, 35,  3, 23, 64, 77, 67, 75],
       [ 4, 79, 87, 51, 92, 45, 45, 60, 47],
       [16, 45, 96,  1, 16, 44, 18, 66, 88]])

In [104]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[53, 75, 32, 34],
       [19, 98, 27, 12],
       [17, 51, 39, 63],
       [33, 73, 63, 16],
       [29, 15, 99, 56]])

In [105]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [106]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [107]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

a2D
[[ 83  32  24  65  80  76  10  36  58]
 [ 65  68  52  47  38  69 100  15  10]
 [ 19  61  38  87  58  84  83  63  70]]

b2D
[[58 37 49 82 93 88 82 99 70]
 [ 5 49 87 65 72 17 73 82 98]
 [50  3 35  3 23 64 77 67 75]
 [ 4 79 87 51 92 45 45 60 47]
 [16 45 96  1 16 44 18 66 88]]

Concatenação
[[ 83  32  24  65  80  76  10  36  58]
 [ 65  68  52  47  38  69 100  15  10]
 [ 19  61  38  87  58  84  83  63  70]
 [ 58  37  49  82  93  88  82  99  70]
 [  5  49  87  65  72  17  73  82  98]
 [ 50   3  35   3  23  64  77  67  75]
 [  4  79  87  51  92  45  45  60  47]
 [ 16  45  96   1  16  44  18  66  88]]


In [110]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

a2D
[[ 83  32  24  65  80  76  10  36  58]
 [ 65  68  52  47  38  69 100  15  10]
 [ 19  61  38  87  58  84  83  63  70]]

b2D
[[58 37 49 82 93 88 82 99 70]
 [ 5 49 87 65 72 17 73 82 98]
 [50  3 35  3 23 64 77 67 75]
 [ 4 79 87 51 92 45 45 60 47]
 [16 45 96  1 16 44 18 66 88]]

Concatenação
[[ 83  32  24  65  80  76  10  36  58]
 [ 65  68  52  47  38  69 100  15  10]
 [ 19  61  38  87  58  84  83  63  70]
 [ 58  37  49  82  93  88  82  99  70]
 [  5  49  87  65  72  17  73  82  98]
 [ 50   3  35   3  23  64  77  67  75]
 [  4  79  87  51  92  45  45  60  47]
 [ 16  45  96   1  16  44  18  66  88]]


In [111]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

b2D
[[58 37 49 82 93 88 82 99 70]
 [ 5 49 87 65 72 17 73 82 98]
 [50  3 35  3 23 64 77 67 75]
 [ 4 79 87 51 92 45 45 60 47]
 [16 45 96  1 16 44 18 66 88]]

c2D
[[53 75 32 34]
 [19 98 27 12]
 [17 51 39 63]
 [33 73 63 16]
 [29 15 99 56]]

Concatenação
[[58 37 49 82 93 88 82 99 70 53 75 32 34]
 [ 5 49 87 65 72 17 73 82 98 19 98 27 12]
 [50  3 35  3 23 64 77 67 75 17 51 39 63]
 [ 4 79 87 51 92 45 45 60 47 33 73 63 16]
 [16 45 96  1 16 44 18 66 88 29 15 99 56]]


In [112]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

b2D
[[58 37 49 82 93 88 82 99 70]
 [ 5 49 87 65 72 17 73 82 98]
 [50  3 35  3 23 64 77 67 75]
 [ 4 79 87 51 92 45 45 60 47]
 [16 45 96  1 16 44 18 66 88]]

c2D
[[53 75 32 34]
 [19 98 27 12]
 [17 51 39 63]
 [33 73 63 16]
 [29 15 99 56]]

Concatenação
[[58 37 49 82 93 88 82 99 70 53 75 32 34]
 [ 5 49 87 65 72 17 73 82 98 19 98 27 12]
 [50  3 35  3 23 64 77 67 75 17 51 39 63]
 [ 4 79 87 51 92 45 45 60 47 33 73 63 16]
 [16 45 96  1 16 44 18 66 88 29 15 99 56]]


### Dividindo arrays

In [113]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

Array original
[[ 83  32  24  65  80  76  10  36  58]
 [ 65  68  52  47  38  69 100  15  10]
 [ 19  61  38  87  58  84  83  63  70]
 [ 58  37  49  82  93  88  82  99  70]
 [  5  49  87  65  72  17  73  82  98]
 [ 50   3  35   3  23  64  77  67  75]
 [  4  79  87  51  92  45  45  60  47]
 [ 16  45  96   1  16  44  18  66  88]]

1a parte
[[ 83  32  24  65  80  76  10  36  58]
 [ 65  68  52  47  38  69 100  15  10]
 [ 19  61  38  87  58  84  83  63  70]
 [ 58  37  49  82  93  88  82  99  70]]

2a parte
[[ 5 49 87 65 72 17 73 82 98]
 [50  3 35  3 23 64 77 67 75]
 [ 4 79 87 51 92 45 45 60 47]
 [16 45 96  1 16 44 18 66 88]]


In [114]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])

Array original
[[ 83  32  24  65  80  76  10  36  58]
 [ 65  68  52  47  38  69 100  15  10]
 [ 19  61  38  87  58  84  83  63  70]
 [ 58  37  49  82  93  88  82  99  70]
 [  5  49  87  65  72  17  73  82  98]
 [ 50   3  35   3  23  64  77  67  75]
 [  4  79  87  51  92  45  45  60  47]
 [ 16  45  96   1  16  44  18  66  88]]

1a parte
[[83 32 24]
 [65 68 52]
 [19 61 38]
 [58 37 49]
 [ 5 49 87]
 [50  3 35]
 [ 4 79 87]
 [16 45 96]]

2a parte
[[65 80 76]
 [47 38 69]
 [87 58 84]
 [82 93 88]
 [65 72 17]
 [ 3 23 64]
 [51 92 45]
 [ 1 16 44]]

3a parte
[[ 10  36  58]
 [100  15  10]
 [ 83  63  70]
 [ 82  99  70]
 [ 73  82  98]
 [ 77  67  75]
 [ 45  60  47]
 [ 18  66  88]]
