# Indexação e fatiamento (slicing)

In [2]:
# Importando o NumPy
import numpy as np

In [3]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([0, 5, 4, 2, 9, 0, 5, 4, 7, 5])

In [6]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[28, 84, 13, 97, 86],
       [44,  2, 83, 65, 34],
       [70, 77, 26, 42, 96],
       [65, 89, 54, 20, 89]])

In [7]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.34171934, 0.8339597 , 0.03695571, 0.68055613, 0.70089488],
        [0.82364133, 0.66185114, 0.92348223, 0.84084473, 0.25489836],
        [0.65403407, 0.71355599, 0.53245425, 0.3028934 , 0.79132007],
        [0.03655929, 0.43771729, 0.99168083, 0.15412501, 0.5639974 ]],

       [[0.15117924, 0.3480522 , 0.33439556, 0.83235788, 0.88646198],
        [0.38891063, 0.68006333, 0.9518965 , 0.05770779, 0.00906035],
        [0.29817167, 0.97172485, 0.75615177, 0.62766121, 0.9487933 ],
        [0.99622766, 0.72179571, 0.06543187, 0.55341912, 0.92809845]],

       [[0.28378185, 0.53526247, 0.82891647, 0.93136354, 0.9435609 ],
        [0.58612036, 0.97738451, 0.57713175, 0.97551895, 0.19342428],
        [0.90920258, 0.3906208 , 0.48165737, 0.08644926, 0.70359055],
        [0.17406712, 0.32951496, 0.21056584, 0.04769685, 0.26143166]]])

### Acessando elementos específicos

In [8]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([0, 5, 4, 2, 9, 0, 5, 4, 7, 5])

In [9]:
# nome_do_array[índice]
a1D[0]

0

In [10]:
a1D[2]

4

In [11]:
a1D[-1]

5

In [12]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([2, 0, 5])

In [13]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[28, 84, 13, 97, 86],
       [44,  2, 83, 65, 34],
       [70, 77, 26, 42, 96],
       [65, 89, 54, 20, 89]])

In [14]:
# nome_da_matriz[linha][coluna]
a2D[1]

array([44,  2, 83, 65, 34])

In [15]:
a2D[3]

array([65, 89, 54, 20, 89])

In [17]:
a2D[3][2]

54

In [25]:
# Diagonal

indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([28,  2, 26, 20])

In [27]:
# Diagonal

indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([97, 83, 77, 65])

In [31]:
# Diagonal

indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([20, 26,  2, 28])

In [33]:
a2D

array([[28, 84, 13, 97, 86],
       [44,  2, 83, 65, 34],
       [70, 77, 26, 42, 96],
       [65, 89, 54, 20, 89]])

In [41]:
query_cols = [0,2,0, 1]
a2D[:, query_cols] 

array([[28, 13, 28, 84],
       [44, 83, 44,  2],
       [70, 26, 70, 77],
       [65, 54, 65, 89]])

In [45]:
a2D[:,query_cols][[1, 0, 1, 0]]

array([[44, 83, 44,  2],
       [28, 13, 28, 84],
       [44, 83, 44,  2],
       [28, 13, 28, 84]])

In [43]:
a2D

array([[28, 84, 13, 97, 86],
       [44,  2, 83, 65, 34],
       [70, 77, 26, 42, 96],
       [65, 89, 54, 20, 89]])

In [46]:
a2D[[1, 0, 1, 0]][:,query_cols] 

array([[44, 83, 44,  2],
       [28, 13, 28, 84],
       [44, 83, 44,  2],
       [28, 13, 28, 84]])

In [47]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.34171934, 0.8339597 , 0.03695571, 0.68055613, 0.70089488],
        [0.82364133, 0.66185114, 0.92348223, 0.84084473, 0.25489836],
        [0.65403407, 0.71355599, 0.53245425, 0.3028934 , 0.79132007],
        [0.03655929, 0.43771729, 0.99168083, 0.15412501, 0.5639974 ]],

       [[0.15117924, 0.3480522 , 0.33439556, 0.83235788, 0.88646198],
        [0.38891063, 0.68006333, 0.9518965 , 0.05770779, 0.00906035],
        [0.29817167, 0.97172485, 0.75615177, 0.62766121, 0.9487933 ],
        [0.99622766, 0.72179571, 0.06543187, 0.55341912, 0.92809845]],

       [[0.28378185, 0.53526247, 0.82891647, 0.93136354, 0.9435609 ],
        [0.58612036, 0.97738451, 0.57713175, 0.97551895, 0.19342428],
        [0.90920258, 0.3906208 , 0.48165737, 0.08644926, 0.70359055],
        [0.17406712, 0.32951496, 0.21056584, 0.04769685, 0.26143166]]])

In [48]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.9313635397551293

In [49]:
a3D[0][3][1]

0.43771728932916965

### Fatiamento (slicing)

In [52]:
# Array de 1 dimensão
a1D

array([0, 5, 4, 2, 9, 0, 5, 4, 7, 5])

In [53]:
a = a1D[1:5] # Índice 1 ao 4
a

array([5, 4, 2, 9])

In [54]:
b = a1D[0:6] # Índice 0 ao 5
b

array([0, 5, 4, 2, 9, 0])

In [55]:
c = a1D[:6] # Do início ao 5
c

array([0, 5, 4, 2, 9, 0])

In [56]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([0, 4, 9, 5, 7])

In [57]:
e = a1D[-1::-1] # Do final até o início
e

array([5, 7, 4, 5, 0, 9, 2, 4, 5, 0])

In [58]:
# Array de 2 dimensões
a2D

array([[28, 84, 13, 97, 86],
       [44,  2, 83, 65, 34],
       [70, 77, 26, 42, 96],
       [65, 89, 54, 20, 89]])

In [59]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([28, 84, 13, 97, 86])

In [60]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([44,  2, 83, 65, 34])

In [61]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([77, 26, 42])

In [63]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([65, 89, 54, 20, 89])

In [64]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([13, 83, 26, 54])

In [65]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([65, 42, 20])

In [66]:
# Array de 3 dimensões
a3D

array([[[0.34171934, 0.8339597 , 0.03695571, 0.68055613, 0.70089488],
        [0.82364133, 0.66185114, 0.92348223, 0.84084473, 0.25489836],
        [0.65403407, 0.71355599, 0.53245425, 0.3028934 , 0.79132007],
        [0.03655929, 0.43771729, 0.99168083, 0.15412501, 0.5639974 ]],

       [[0.15117924, 0.3480522 , 0.33439556, 0.83235788, 0.88646198],
        [0.38891063, 0.68006333, 0.9518965 , 0.05770779, 0.00906035],
        [0.29817167, 0.97172485, 0.75615177, 0.62766121, 0.9487933 ],
        [0.99622766, 0.72179571, 0.06543187, 0.55341912, 0.92809845]],

       [[0.28378185, 0.53526247, 0.82891647, 0.93136354, 0.9435609 ],
        [0.58612036, 0.97738451, 0.57713175, 0.97551895, 0.19342428],
        [0.90920258, 0.3906208 , 0.48165737, 0.08644926, 0.70359055],
        [0.17406712, 0.32951496, 0.21056584, 0.04769685, 0.26143166]]])

In [67]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.15117924, 0.3480522 , 0.33439556, 0.83235788, 0.88646198],
       [0.38891063, 0.68006333, 0.9518965 , 0.05770779, 0.00906035],
       [0.29817167, 0.97172485, 0.75615177, 0.62766121, 0.9487933 ],
       [0.99622766, 0.72179571, 0.06543187, 0.55341912, 0.92809845]])

In [70]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.3480522 , 0.33439556, 0.83235788],
       [0.68006333, 0.9518965 , 0.05770779],
       [0.97172485, 0.75615177, 0.62766121]])

In [71]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.65403407, 0.71355599, 0.53245425, 0.3028934 , 0.79132007])

In [ ]:
a3D

In [72]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.82364133, 0.66185114, 0.92348223, 0.84084473, 0.25489836],
       [0.38891063, 0.68006333, 0.9518965 , 0.05770779, 0.00906035],
       [0.58612036, 0.97738451, 0.57713175, 0.97551895, 0.19342428]])

In [73]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.68055613, 0.84084473, 0.3028934 , 0.15412501],
       [0.83235788, 0.05770779, 0.62766121, 0.55341912],
       [0.93136354, 0.97551895, 0.08644926, 0.04769685]])

### Indexação com booleanos

In [75]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 10 linhas x 8 colunas com elementos entre 1 e 100
a2D

array([[ 20,  16, 468,  16, 230,  84, 200, 469],
       [221, 447, 182, 297, 379,  99, 152,  17],
       [113, 397, 173, 312, 334, 135, 471, 322],
       [327, 240, 259,   5,  90, 336, 350, 333],
       [382, 418,  56, 162, 399, 453, 430,  76],
       [295, 419, 183, 383, 173, 223, 480, 380],
       [450,  92, 478, 275, 162, 111, 170,  97],
       [365, 439, 316, 151, 394, 454,   6, 378],
       [ 76, 395, 188,  80, 256,  36, 470, 181],
       [100, 282, 394, 406, 312, 306,  98, 261]])

In [76]:
a2D >= 250

array([[False, False,  True, False, False, False, False,  True],
       [False,  True, False,  True,  True, False, False, False],
       [False,  True, False,  True,  True, False,  True,  True],
       [ True, False,  True, False, False,  True,  True,  True],
       [ True,  True, False, False,  True,  True,  True, False],
       [ True,  True, False,  True, False, False,  True,  True],
       [ True, False,  True,  True, False, False, False, False],
       [ True,  True,  True, False,  True,  True, False,  True],
       [False,  True, False, False,  True, False,  True, False],
       [False,  True,  True,  True,  True,  True, False,  True]])

In [77]:
a2D[a2D >= 250]

array([468, 469, 447, 297, 379, 397, 312, 334, 471, 322, 327, 259, 336,
       350, 333, 382, 418, 399, 453, 430, 295, 419, 383, 480, 380, 450,
       478, 275, 365, 439, 316, 394, 454, 378, 395, 256, 470, 282, 394,
       406, 312, 306, 261])

In [78]:
a2D.mean()

257.3125

In [79]:
a2D[a2D <= a2D.mean()]

array([ 20,  16,  16, 230,  84, 200, 221, 182,  99, 152,  17, 113, 173,
       135, 240,   5,  90,  56, 162,  76, 183, 173, 223,  92, 162, 111,
       170,  97, 151,   6,  76, 188,  80, 256,  36, 181, 100,  98])